# Build stage
FROM alpine:3.21.3

RUN apk --no-cache add ca-certificates

WORKDIR /app/

# The binary is now copied by GoReleaser
COPY bulwarkauthadmin /app/
COPY verification.html magic.html forgot.html /app/

ENV PORT=8080
EXPOSE $PORT

# Health check
HEALTHCHECK --interval=30s --timeout=3s \
  CMD wget --no-verbose --tries=1 --spider http://localhost:${PORT}/health || exit 1

ENTRYPOINT ["/app/bulwarkauthadmin"]
